[package]
name = "mpc_valet"
version = "0.1.2-dev"
edition = "2021"
authors = ["Pierre Lulé <pierre@lule.fr>"]
description = "A tool for creating instrument for MPC drum machines."
readme = "README.md"
repository = "https://github.com/plule/mpc_valet"
license = "MIT OR Apache-2.0"

[[bin]]
name = "mpc_valet_bin"
path = "src/main.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
music-note = "0.3.0"
regex = "1"
xmltree = "0.10.3"
glob = "0.3.0"
egui = "0.18.0"
egui_extras = "0.18.0"
eframe = "0.18.0"
lazy_static = "1.4.0"
itertools = "0.10.3"

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tracing-subscriber = "0.3"
rfd = "0.8.2"

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
tracing-wasm = "0.2"
js-sys = "0.3.57"
web-sys = {version = "0.3.57", features = ["Document", "Window", "Node", "HtmlElement", "Element"]}

[dev-dependencies]
rstest = "0.12.0"

[profile.release]
opt-level = 2 # fast and small wasm
