[package]
name = "mpc_keygroup_creator"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mpc_keygroup_creator_bin"
path = "src/main.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
music-note = "0.3.0"
regex = "1"
xmltree = "0.10.3"
glob = "0.3.0"
egui = "0.18.0"
eframe = "0.18.0"

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tracing-subscriber = "0.3"

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
tracing-wasm = "0.2"

[dev-dependencies]
rstest = "0.12.0"

[profile.release]
opt-level = 2 # fast and small wasm
