[package]
name = "mpc_valet"
version = "0.3.1-dev"
edition = "2021"
authors = ["Pierre Lulé <pierre@lule.fr>"]
description = "A tool for creating instrument for MPC drum machines."
readme = "README.md"
repository = "https://github.com/plule/mpc_valet"
license = "MIT OR Apache-2.0"

[dependencies]
music-note = "0.3.0"
regex = "1"
xmltree = "0.10.3"
lazy_static = "1.4.0"
itertools = "0.10.3"
anyhow = "1.0.57"
rulex-macro = "0.4.3"
yew = "0.19"
yew-utils = "0.2"
log = "0.4.17"
wasm-logger = "0.2.0"
wasm-bindgen = "0.2.81"
js-sys = "0.3.58"

[dependencies.web-sys]
version = "0.3"
features = [
	"HtmlInputElement",
	"DragEvent",
	"DataTransfer",
	"FileList",
	"File",
]

[dev-dependencies]
rstest = "0.15.0"

[profile.release]
opt-level = 2 # fast and small wasm
