name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  create:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v1
    
    - name: Build deps
      run: sudo apt-get update && sudo apt-get install -y libatk1.0-dev libgtk-3-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libssl-dev
    - name: Install wasm toolchain
      run: rustup target add wasm32-unknown-unknown
    - name: Install wasm bindgen
      run: cargo install wasm-bindgen-cli
    - name: Run tests
      run: cargo test --verbose
    - name: Build for web
      run: cargo build --release --lib --target wasm32-unknown-unknown
    - name: Wasm bindgen
      run: wasm-bindgen --out-dir ./docs/ --no-modules --no-typescript ./target/wasm32-unknown-unknown/release/mpc_valet.wasm
    - name: Deploy to github pages
      if: startsWith(github.ref, 'refs/tags/v')
      uses: JamesIves/github-pages-deploy-action@v4.3.0
      with:
        branch: gh-pages
        folder: docs
    - name: Publish crate
      if: startsWith(github.ref, 'refs/tags/v')
      run: cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
